[2024-04-02T07:32:03.598+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_crime_process_dag.create_dataproc_cluster manual__2024-03-29T11:33:06.238124+00:00 [queued]>
[2024-04-02T07:32:03.607+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_crime_process_dag.create_dataproc_cluster manual__2024-03-29T11:33:06.238124+00:00 [queued]>
[2024-04-02T07:32:03.608+0000] {taskinstance.py:2193} INFO - Starting attempt 9 of 10
[2024-04-02T07:32:03.623+0000] {taskinstance.py:2214} INFO - Executing <Task(DataprocCreateClusterOperator): create_dataproc_cluster> on 2024-03-29 11:33:06.238124+00:00
[2024-04-02T07:32:03.631+0000] {standard_task_runner.py:60} INFO - Started process 1753 to run task
[2024-04-02T07:32:03.635+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_crime_process_dag', 'create_dataproc_cluster', 'manual__2024-03-29T11:33:06.238124+00:00', '--job-id', '647', '--raw', '--subdir', 'DAGS_FOLDER/data_transformation.py', '--cfg-path', '/tmp/tmp9u928ox2']
[2024-04-02T07:32:03.637+0000] {standard_task_runner.py:88} INFO - Job 647: Subtask create_dataproc_cluster
[2024-04-02T07:32:03.677+0000] {task_command.py:423} INFO - Running <TaskInstance: data_crime_process_dag.create_dataproc_cluster manual__2024-03-29T11:33:06.238124+00:00 [running]> on host 0f6b1d3e95d8
[2024-04-02T07:32:03.749+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_crime_process_dag' AIRFLOW_CTX_TASK_ID='create_dataproc_cluster' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T11:33:06.238124+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T11:33:06.238124+00:00'
[2024-04-02T07:32:03.751+0000] {dataproc.py:778} INFO - Creating cluster: dataproc-cluster
[2024-04-02T07:32:03.752+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-04-02T07:32:03.753+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-02T07:32:03.754+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-04-02T07:34:52.536+0000] {dataproc.py:799} INFO - Cluster created.
[2024-04-02T07:34:52.566+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=data_crime_process_dag, task_id=create_dataproc_cluster, execution_date=20240329T113306, start_date=20240402T073203, end_date=20240402T073452
[2024-04-02T07:34:52.593+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-02T07:34:52.612+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
