[2024-03-18T07:10:53.957+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: two_separate_groups.bigquery_external_table_4_task scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-03-18T07:10:53.967+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: two_separate_groups.bigquery_external_table_4_task scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-03-18T07:10:53.967+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-03-18T07:10:53.979+0000] {taskinstance.py:2214} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_4_task> on 2024-03-17 00:00:00+00:00
[2024-03-18T07:10:53.986+0000] {standard_task_runner.py:60} INFO - Started process 934 to run task
[2024-03-18T07:10:53.989+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'two_separate_groups', 'bigquery_external_table_4_task', 'scheduled__2024-03-17T00:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_to_gcs.py', '--cfg-path', '/tmp/tmp04g43_u8']
[2024-03-18T07:10:53.990+0000] {standard_task_runner.py:88} INFO - Job 263: Subtask bigquery_external_table_4_task
[2024-03-18T07:10:54.030+0000] {task_command.py:423} INFO - Running <TaskInstance: two_separate_groups.bigquery_external_table_4_task scheduled__2024-03-17T00:00:00+00:00 [running]> on host 9958f290dc4a
[2024-03-18T07:10:54.102+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='two_separate_groups' AIRFLOW_CTX_TASK_ID='bigquery_external_table_4_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T00:00:00+00:00'
[2024-03-18T07:10:54.105+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-03-18T07:10:54.105+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-18T07:10:54.106+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-18T07:10:54.545+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=two_separate_groups, task_id=bigquery_external_table_4_task, execution_date=20240317T000000, start_date=20240318T071053, end_date=20240318T071054
[2024-03-18T07:10:54.606+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-18T07:10:54.637+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
